[package]
name = "stalinsort"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
parameterized = "2.0.0"

[dependencies]
rand = "0.8.5"
sorting_rs = "1.2.10"
